import torch
import torch._inductor.fx_passes.joint_graph as joint_graph


def patch_constant_fold_uniform_value():
    # Fix bug in aot_inductor for torch.
    # Eliminate dead-nodes to remove extra constants generated by torch.tensor.
    src_func = joint_graph.constant_fold_uniform_value

    def new_constant_fold_uniform_value(gm):
        src_func(gm)
        if isinstance(gm, torch.fx.GraphModule):
            gm.graph.eliminate_dead_code()
    
    joint_graph.constant_fold_uniform_value = new_constant_fold_uniform_value