import functools

import torch
import torch._inductor.fx_passes.joint_graph as joint_graph
import torch.utils._pytree as pytree


def _is_npu_graph(gm):
    if not isinstance(gm, torch.fx.GraphModule):
        return False

    return any(
        getattr(getattr(value, "device", None), "type", None) == "npu"
        for node in gm.graph.nodes
        for value in pytree.tree_leaves(node.meta.get("val"))
    )


def patch_constant_fold_uniform_value():
    # Fix bug in aot_inductor for torch.
    # Eliminate dead-nodes to remove extra constants generated by torch.tensor.
    src_func = joint_graph.constant_fold_uniform_value

    @functools.wraps(src_func)
    def new_constant_fold_uniform_value(gm):
        is_npu_graph = _is_npu_graph(gm)
        result = src_func(gm)
        if is_npu_graph:
            gm.graph.eliminate_dead_code()
        return result

    joint_graph.constant_fold_uniform_value = new_constant_fold_uniform_value
