import functools
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import torch
from torch._inductor.autoheuristic.autoheuristic import AutoHeuristicSelectAlgorithm
from torch._inductor.autoheuristic.autoheuristic_utils import (
    mm_operations,
)
import torch._inductor.codegen
from torch._inductor.codegen.cpp_gemm_template import CppGemmTemplate
import torch._inductor.kernel
from torch._inductor.virtualized import V

from torch._inductor import config as inductor_config, ir
from torch._inductor.codegen.common import BackendFeature
from torch._inductor.codegen.rocm.ck_universal_gemm_template import CKGemmTemplate
from torch._inductor.codegen.wrapper import PythonWrapperCodegen
from torch._inductor.ir import FixedLayout, FlexibleLayout, is_triton
from torch._inductor.lowering import register_lowering, fallback_handler
from torch._inductor.select_algorithm import (
    autotune_select_algorithm,
    ExternKernelChoice,
    NoValidChoicesError,
    TritonTemplate,
)
from torch._inductor.utils import (
    load_template,
    use_aten_gemm_kernels,
    use_ck_gemm_template,
    use_cpp_gemm_template,
    is_pointwise_use,
)
from torch._inductor.kernel.mm_common import (
    _is_static_problem,
    addmm_epilogue,
    mm_args,
    mm_grid,
)
# Note: addmm_epilogue is imported above and used to build the epilogue_fn
# that fuses `beta * bias + alpha * acc` into the template's store_output.
from torch._inductor.select_algorithm import SymbolicGridFn

from ..codegen.catlass.gemm_template import CATLASS1xGemmTemplate
from ..select_algorithm import NPUTritonTemplate
from ..utils import use_catlass_template, use_triton_template


log = logging.getLogger("torch._inductor")
aten = torch.ops.aten

lazy_register_extern_choice = torch._inductor.kernel.mm.lazy_register_extern_choice
aten_mm = torch._inductor.kernel.mm.aten_mm
aten_addmm = torch._inductor.kernel.mm.aten_addmm
mm_template = torch._inductor.kernel.mm.mm_template


# ---------------------------------------------------------------------------
# NPU Triton MM Template (for CV / epilogue fusion)
# ---------------------------------------------------------------------------
# Following the community torch design:
#   - The jinja template lives in templates/triton_mm.py.jinja
#   - The NPUTritonTemplate instance is created here, loading that jinja file
#   - Tiling configs are generated by _get_npu_mm_configs() below
#   - Choices are added in tuned_mm() via add_npu_triton_mm_choices()
#
# When the scheduler detects that the matmul output is consumed by pointwise
# ops (add, relu, etc.), it fuses them into the template's {{store_output}}
# epilogue — this is the "CV fusion" mechanism.
# ---------------------------------------------------------------------------

_MM_TEMPLATE = """{{def_kernel("A", "B")}}
    M = {{size("A", 0)}}
    N = {{size("B", 1)}}
    K = {{size("A", 1)}}
    if M * N == 0:
        # early exit due to zero-size input(s)
        return
    stride_am = {{stride("A", 0)}}
    stride_ak = {{stride("A", 1)}}
    stride_bk = {{stride("B", 0)}}
    stride_bn = {{stride("B", 1)}}

    # based on triton.ops.matmul
    pid = tl.program_id(0).to(INDEX_DTYPE)
    grid_m = (M + BLOCK_M - 1) // BLOCK_M
    grid_n = (N + BLOCK_N - 1) // BLOCK_N

    # re-order program ID for better L2 performance
    # Use super-grouping (GROUP_M) for improved L2 cache hit rate
    width = GROUP_M * grid_n
    group_id = pid // width
    group_size = min(grid_m - group_id * GROUP_M, GROUP_M)
    pid_m = group_id * GROUP_M + (pid % group_size)
    pid_n = (pid % width) // group_size

    tl.assume(pid_m >= 0)
    tl.assume(pid_n >= 0)

    rm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    rn = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    # Pre-compute row mask once; reused in both K-loop and epilogue.
    m_mask = rm < M

    offs_k = tl.arange(0, BLOCK_K)
    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=ACC_TYPE)

    for k_idx in range(0, tl.cdiv(K, BLOCK_K)):
        offs_a_k = k_idx * BLOCK_K + tl.arange(0, BLOCK_K)
        {% if EVEN_K %}
        a = tl.load(A + (rm[:, None] * stride_am + offs_a_k[None, :] * stride_ak))
        b = tl.load(B + (offs_a_k[:, None] * stride_bk + rn[None, :] * stride_bn))
        {% else %}
        # K is not a multiple of BLOCK_K: mask out-of-bounds elements
        k_mask = offs_a_k < K
        a = tl.load(A + (rm[:, None] * stride_am + offs_a_k[None, :] * stride_ak), mask=k_mask[None, :], other=0.0)
        b = tl.load(B + (offs_a_k[:, None] * stride_bk + rn[None, :] * stride_bn), mask=k_mask[:, None], other=0.0)
        {% endif %}
        acc += tl.dot(a, b, allow_tf32=ALLOW_TF32, out_dtype=ACC_TYPE)

    # rm, rn, and m_mask are reused from above (no rematerialization).
    idx_m = rm[:, None]
    idx_n = rn[None, :]
    mask = (idx_m < M) & (idx_n < N)

    {{npu_register_1d("idx_m", "rm", "m_mask")}}
    {{npu_register_1d("idx_n", "rn", None)}}

    # inductor generates a suffix
    {{store_output(("idx_m", "idx_n"), "acc", "mask", val_shape=("BLOCK_M", "BLOCK_N"))}}
"""


npu_triton_mm_template = NPUTritonTemplate(
    name="npu_triton_mm",
    grid=mm_grid,
    source=_MM_TEMPLATE,
    debug=False,
)


# ---------------------------------------------------------------------------
# NPU Persistent Triton MM Template (diagonal core division)
# ---------------------------------------------------------------------------
# Uses new_triton_mm.py.jinja which implements a persistent kernel strategy:
# each program handles multiple tiles via `for block_idx in range(pid, NUM_BLOCKS, num_cores)`.
# For large matrices (NUM_BLOCKS_M >= 8 and NUM_BLOCKS_N >= 8), a diagonal
# super-grouping strategy improves L2 cache hit rate.
# The {{store_output}} placeholder is inside the for loop, so indent_width=8.

# ===================================================================
# Persistent kernel with super-grouping (diagonal tile traversal)
# ===================================================================
# Inspired by the community persistent_tma_mm template but adapted
# for Ascend NPU (no TMA — uses plain tl.load).
#
# Core idea:
#   * Launch NUM_SMS programs (one per AI Core).
#   * Each program serially processes multiple output tiles:
#       tile_id = start_pid, start_pid + NUM_SMS, start_pid + 2*NUM_SMS, ...
#   * Super-grouping (GROUP_M) reorders tiles so that programs running
#     concurrently access overlapping rows of A, improving L2 cache
#     hit rate.
#
# Key NPU constraint: GROUP_M is guaranteed to be a factor of
# NUM_BLOCKS_M (enforced in config generation), so every modulo /
# division below is (runtime) op (compile-time constant) — safe for
# the NPU Triton backend.
# ===================================================================

_PERSISTENT_MM_TEMPLATE = """
{{def_kernel("A", "B")}}
    M = {{size("A", 0)}}
    N = {{size("B", 1)}}
    K = {{size("A", 1)}}
    if M * N == 0:
        # early exit due to zero-size input(s)
        return
    stride_am = {{stride("A", 0)}}
    stride_ak = {{stride("A", 1)}}
    stride_bk = {{stride("B", 0)}}
    stride_bn = {{stride("B", 1)}}

    start_pid = tl.program_id(0).to(INDEX_DTYPE)

    # Offsets shared across all tiles handled by this program
    rk_init = tl.arange(0, BLOCK_K)

    # Iterate over the tiles assigned to this program.
    # NUM_TILES_PER_PROGRAM is a compile-time constant (= ceil(NUM_BLOCKS / NUM_SMS)).
    for tile_iter in range(NUM_TILES_PER_PROGRAM):
        tile_id = start_pid + tile_iter * NUM_SMS
        if tile_id < NUM_BLOCKS:
            # ---- Super-grouping tile reordering ----
            # Map linear tile_id → (pid_m, pid_n) with diagonal traversal.
            # WIDTH = GROUP_M * NUM_BLOCKS_N (compile-time constant).
            group_id = tile_id // WIDTH
            pid_m = group_id * GROUP_M + (tile_id % GROUP_M)
            pid_n = (tile_id % WIDTH) // GROUP_M

            rm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
            rn = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
            # Pre-compute row mask once; reused in both K-loop and epilogue.
            # This avoids redundant comparisons and enables 1D load masking
            # for broadcast inputs (e.g. bias[N], mask[M]) in the epilogue.
            m_mask = rm < M

            # ---- K-loop: accumulate matmul ----
            acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=ACC_TYPE)
            for k_start in range(0, K, BLOCK_K):
                offs_k = k_start + rk_init
                {% if EVEN_K %}
                a = tl.load(A + (rm[:, None] * stride_am + offs_k[None, :] * stride_ak))
                b = tl.load(B + (offs_k[:, None] * stride_bk + rn[None, :] * stride_bn))
                {% else %}
                k_mask = offs_k < K
                a = tl.load(A + (rm[:, None] * stride_am + offs_k[None, :] * stride_ak), mask=k_mask[None, :], other=0.0)
                b = tl.load(B + (offs_k[:, None] * stride_bk + rn[None, :] * stride_bn), mask=k_mask[:, None], other=0.0)
                {% endif %}
                acc += tl.dot(a, b, allow_tf32=ALLOW_TF32, out_dtype=ACC_TYPE)

            # ---- Store output (inductor generates epilogue suffix) ----
            # rm, rn, and m_mask are reused from above (no rematerialization).
            idx_m = rm[:, None]
            idx_n = rn[None, :]
            mask = (idx_m < M) & (idx_n < N)

            {{npu_register_1d("idx_m", "rm", "m_mask")}}
            {{npu_register_1d("idx_n", "rn", None)}}
            {{store_output(("idx_m", "idx_n"), "acc", "mask", val_shape=("BLOCK_M", "BLOCK_N"), indent_width=12)}}
"""


@SymbolicGridFn
def npu_persistent_mm_grid(M: int, N: int, meta: Dict[str, Any], *, cdiv, min):
    """Grid function for persistent mm template.

    Launches min(NUM_BLOCKS, NUM_SMS) programs. Each program iterates
    over multiple tiles via `tile_id = start_pid + tile_iter * NUM_SMS`.
    """
    num_blocks = cdiv(M, meta["BLOCK_M"]) * cdiv(N, meta["BLOCK_N"])
    return (min(num_blocks, meta["NUM_SMS"]), 1, 1)


npu_persistent_mm_template = NPUTritonTemplate(
    name="npu_persistent_mm",
    grid=npu_persistent_mm_grid,
    source=_PERSISTENT_MM_TEMPLATE,
    debug=False,
)


# ---------------------------------------------------------------------------
# Dynamic-shape helpers
# ---------------------------------------------------------------------------
# When torch.compile(dynamic=True) is used, M / N / K arrive as symbolic
# sympy expressions (e.g. ``s97``) rather than concrete ints.  The config
# generation functions below need concrete values for two purposes:
#
#   1. GROUP_M selection  (non-persistent template) — a *hint* is safe
#      because GROUP_M only influences L2 cache super-grouping; the actual
#      grid is recomputed at runtime inside the kernel.
#
#   2. NUM_BLOCKS / NUM_TILES_PER_PROGRAM / WIDTH  (persistent template) —
#      these are baked into the kernel as ``tl.constexpr`` and **must**
#      match the real runtime shape, so a hint is *not* safe; the
#      persistent template is skipped entirely for dynamic shapes.
# ---------------------------------------------------------------------------

def _is_symbolic_dim(val) -> bool:
    """Return True if *val* is a symbolic (non-statically-known) dimension.

    Uses the same utility that ``_is_static_problem`` relies on
    (``PythonWrapperCodegen.statically_known_int_or_none``), so plain
    ints and sympy integers are considered static, while expressions
    with free symbols (e.g. ``s97``) are considered symbolic.
    """
    return PythonWrapperCodegen.statically_known_int_or_none(val) is None


def _hint_int(val, fallback: int = 1) -> int:
    """Resolve a (possibly symbolic) dimension to a concrete int hint.

    For statically-known dimensions the actual value is returned.
    For symbolic dimensions ``V.graph.sizevars.size_hint`` is used to
    obtain a concrete estimate from the tracing context's example
    inputs (the same mechanism that ``use_catlass_template`` uses for
    ``size_hint(m * n * k)``).

    This is only safe for **config selection** (choosing GROUP_M, tile
    sizes, etc.) — never for values that must match the runtime shape
    exactly (such as the persistent template's NUM_BLOCKS).
    """
    static = PythonWrapperCodegen.statically_known_int_or_none(val)
    if static is not None:
        return static
    try:
        return V.graph.sizevars.size_hint(val)
    except Exception:
        return fallback


# ---------------------------------------------------------------------------
# Dynamic tile config generation helpers
# ---------------------------------------------------------------------------
# Inspired by catlass's gemm_autotune.py generate_configs() logic and
# the tiling optimization principles from optimization_summary.md:
#
#   1. BLOCK_M should ideally divide M (eliminates padding — biggest win)
#   2. BLOCK_N uses standard 16-aligned values (64, 128, 256)
#   3. BLOCK_K uses divisors of K (mult of 16) or standards (64, 128)
#   4. num_stages scales with K-loop iteration count
#   5. GROUP_M is the largest factor of NUM_BLOCKS_M ≤ 8
#
# This replaces the previous hardcoded tile_shapes list with a shape-aware
# generator, significantly reducing the number of autotune configs while
# improving coverage of good tilings (e.g. BLOCK_M=100 for M=200).
# ---------------------------------------------------------------------------

def _get_divisors(n, min_val=1, max_val=None):
    """Get all divisors of *n* in [min_val, max_val], sorted descending.

    Used to find BLOCK_M / BLOCK_N values that perfectly divide the
    matrix dimension (eliminating padding).
    """
    if max_val is None:
        max_val = n
    if n < 1:
        return []
    divs = set()
    i = 1
    while i * i <= n:
        if n % i == 0:
            if min_val <= i <= max_val:
                divs.add(i)
            j = n // i
            if min_val <= j <= max_val:
                divs.add(j)
        i += 1
    return sorted(divs, reverse=True)


def _gen_block_m_candidates(m, max_block_dim, max_count=5):
    """Generate BLOCK_M candidates for dimension *m*.

    Combines:
      * **Divisors of M** in [16, min(M, max_block_dim)] — preferred
        because they eliminate M-padding (the single biggest perf win
        per optimization_summary.md, e.g. BLOCK_M=100 for M=200).
      * **16-aligned standard values** (256, 128, 64, 32) as fallbacks
        for shapes where M has few useful divisors.

    Guarantees at least one candidate for any positive *m* (using the
    minimum tile size 16 with row masking when M < 16), so that tiling
    config generation never produces an empty candidate set.

    Returns at most *max_count* candidates, sorted descending.
    """
    effective_max = min(m, max_block_dim)
    # Fallback for very small M: use the minimum tile size (16) with
    # row masking (m_mask = rm < M in the kernel template).  This
    # guarantees a non-empty candidate set for any positive M.
    if effective_max < 16:
        if max_block_dim >= 16:
            return [16]
        # max_block_dim < 16 (extremely rare): use max_block_dim itself
        # so we always return at least one positive candidate.
        return [max(max_block_dim, 1)]

    # Divisors of M (preferred — eliminate padding)
    divs = _get_divisors(m, 16, effective_max)
    # 16-aligned standards as fallback
    standards = [s for s in [256, 128, 64, 32] if s <= effective_max]

    merged = []
    seen = set()
    # Top 3 divisors (padding-eliminating)
    for d in divs[:3]:
        if d not in seen:
            merged.append(d)
            seen.add(d)
    # Top standard (largest, for compute density)
    for s in standards[:1]:
        if s not in seen:
            merged.append(s)
            seen.add(s)
    # Always include smallest standard (e.g. 32) — optimal for small-N shapes
    if standards and standards[-1] not in seen:
        merged.append(standards[-1])
        seen.add(standards[-1])
    # Safety net: if both divs and standards were empty (should not happen
    # here since effective_max >= 16), fall back to 16.
    if not merged:
        merged.append(16)
    return sorted(merged, reverse=True)[:max_count]


def _gen_block_n_candidates(n, max_block_dim, max_count=3):
    """Generate BLOCK_N candidates for dimension *n*.

    Primarily uses 16-aligned standard values (256, 128, 64, 32) ≤ N,
    plus divisors of N for padding elimination when N is not a round
    number.

    Guarantees at least one candidate for any positive *n* (using the
    minimum tile size 16 with column masking when N < 16), so that
    tiling config generation never produces an empty candidate set.

    Returns at most *max_count* candidates, sorted descending.
    """
    effective_max = min(n, max_block_dim)
    # Fallback for very small N: use the minimum tile size (16) with
    # column masking (idx_n < N in the kernel template).  This
    # guarantees a non-empty candidate set for any positive N.
    if effective_max < 16:
        if max_block_dim >= 16:
            return [16]
        # max_block_dim < 16 (extremely rare): use max_block_dim itself.
        return [max(max_block_dim, 1)]

    cands = set()
    # Standards (primary)
    for s in [256, 128, 64, 32]:
        if s <= effective_max:
            cands.add(s)
    # Divisors of N (secondary — for non-round N)
    for d in _get_divisors(n, 16, effective_max):
        cands.add(d)
    # Safety net: if both standards and divisors were empty (should not
    # happen here since effective_max >= 16), fall back to 16.
    if not cands:
        cands.add(16)
    return sorted(cands, reverse=True)[:max_count]


def _gen_block_k_candidates(k, max_count=3):
    """Generate BLOCK_K candidates for dimension *k*.

    Combines:
      * **Standards** [128, 64, 32] (always useful, good pipelining).
      * **256** when K ≥ 128 — allows a single-iteration K-loop
        (ceil(K/256)=1) which eliminates loop overhead for
        mid-range K values (e.g. K=204, K=128).
      * **K itself** if 16 ≤ K ≤ 256 and K is a multiple of 16.
      * **K/n** for n in {2, 3, 4} if the result is a multiple of 16
        and in [16, 256] — these reduce K-loop iterations while
        keeping EVEN_K=True (no K-mask overhead).

    Guarantees at least one candidate for any positive *k*.
    For small or non-standard K values (e.g. K=7, K=16, K=17) where
    none of the above rules produce a candidate, falls back to the
    minimum tile size 16 (the smallest fp16 MMA tile), which works
    correctly with EVEN_K=False K-masking in the kernel template.

    Returns at most *max_count* candidates, sorted descending.
    """
    cands = set()
    # Standards — includes 32 for better small-K coverage
    for std in [128, 64, 32]:
        if std <= k:
            cands.add(std)
    # Include 256 when K is large enough (allows 1-iteration K-loop,
    # eliminating loop overhead for mid-range K).
    if k >= 128:
        cands.add(256)
    # K itself (if nice — multiple of 16 and >= 16)
    if 16 <= k <= 256 and k % 16 == 0:
        cands.add(k)
    # K / n for small n (reduce K-loop iters, keep EVEN_K)
    for divisor in (2, 3, 4):
        if k % divisor == 0:
            dk = k // divisor
            if 16 <= dk <= 256 and dk % 16 == 0:
                cands.add(dk)
    # ---- Fallback: ensure at least one candidate for any K > 0 ----
    # For small or non-standard K (e.g. K=7, K=17, prime K), none of
    # the rules above may produce a candidate.  Use 16 — the minimum
    # tile size for fp16 MMA — with EVEN_K=False K-masking (the kernel
    # template's {% else %} branch handles k_mask = offs_k < K).
    # This guarantees tiling config generation never returns empty.
    if not cands:
        cands.add(16)
    return sorted(cands, reverse=True)[:max_count]


def _select_num_stages(k_iters, block_k):
    """Select num_stages list based on K-loop iteration count.

    Deeper pipelines (more stages) help when there are many K
    iterations (more parallelism to exploit). For BLOCK_K ≥ 256,
    limit stages to avoid register overflow.

    Per optimization_summary.md:
      * K iters ≥ 10 (e.g. K=1920, 15 iters): num_stages up to 6
      * K iters 2-9: num_stages 3-4
      * K iters = 1: num_stages 2-3
    """
    if block_k >= 256:
        return [2]  # avoid register overflow for large BLOCK_K
    if k_iters >= 10:
        return [4, 6]  # very deep pipeline for many K iters
    if k_iters >= 2:
        return [3, 4]
    return [2, 3]


def _gen_tile_combos(m, n, k, max_block_dim):
    """Generate a focused set of (BLOCK_M, BLOCK_N, BLOCK_K) tile combos.

    Uses the dynamic candidate generators above and combines them into
    a limited Cartesian product, filtered by the L0C tile-area
    constraint (BLOCK_M × BLOCK_N ≤ 64K elements for fp32 accumulator).

    Guarantees at least one valid combo for any positive M, N, K (the
    candidate generators never return empty lists, and a final safety
    net appends the smallest combo if all larger ones are filtered out
    by the tile-area constraint).

    Returns a list of (BLOCK_M, BLOCK_N, BLOCK_K) tuples.
    """
    block_m_cands = _gen_block_m_candidates(m, max_block_dim)
    block_n_cands = _gen_block_n_candidates(n, max_block_dim)
    block_k_cands = _gen_block_k_candidates(k)

    # L0C constraint: accumulator is fp32 (4 bytes), L0C ≈ 256 KB
    # → max tile area ≈ 64K elements
    MAX_TILE_AREA = 256 * 1024 // 4  # 65536

    combos = []
    for block_m in block_m_cands:
        for block_n in block_n_cands[:3]:  # top 3 N candidates per M
            if block_m * block_n > MAX_TILE_AREA:
                continue
            for block_k in block_k_cands[:2]:  # top 2 K candidates
                combos.append((block_m, block_n, block_k))

    # ---- Safety net: guarantee at least one valid combo ----
    # If all combos were filtered out by the tile-area constraint (only
    # possible when the smallest candidate tiles still exceed 64K —
    # extremely unlikely since 16*16 = 256 << 65536), fall back to the
    # smallest available tiles which always fit.
    if not combos and block_m_cands and block_n_cands and block_k_cands:
        smallest_m = block_m_cands[-1]
        smallest_n = block_n_cands[-1]
        smallest_k = block_k_cands[-1]
        combos.append((smallest_m, smallest_n, smallest_k))

    return combos


def _get_npu_mm_configs(
    m: int,
    n: int,
    k: int,
    *,
    max_block_dim: int = 256,
) -> List[Dict[str, Any]]:
    """Generate tiling configs for NPU triton matmul template (dynamic).

    Dynamically computes (BLOCK_M, BLOCK_N, BLOCK_K, GROUP_M, num_stages)
    configurations based on the actual M, N, K shape,
    following the optimization principles in optimization_summary.md:

      1. BLOCK_M prioritises divisors of M to eliminate padding
         (e.g. BLOCK_M=100 for M=200 — the single biggest perf win).
      2. BLOCK_N uses standard 16-aligned values (64, 128, 256).
      3. BLOCK_K uses divisors of K (mult of 16) or standards (64, 128).
      4. num_stages scales with K-loop iteration count.
      5. GROUP_M is the largest factor of NUM_BLOCKS_M ≤ 8.

    This replaces the previous hardcoded tile_shapes list with a
    shape-aware generator, significantly reducing the number of
    autotune configs while improving coverage of good tilings.

    Args:
        max_block_dim: Cap BLOCK_M and BLOCK_N at this value.  Set to 128
            for addmm (the bias epilogue fusion adds register pressure).
    """
    # Resolve m/n/k to concrete hints for tile selection.
    # GROUP_M only affects L2 cache super-grouping behaviour, not kernel
    # correctness — the actual grid (grid_m, grid_n) is computed at runtime
    # inside the kernel from the real M, N values.  Using a hint here simply
    # picks a reasonable GROUP_M for the expected shape.
    m_hint = _hint_int(m)
    n_hint = _hint_int(n)
    k_hint = _hint_int(k)

    configs: List[Dict[str, Any]] = []

    # Dynamically generate tile combos based on the actual shape.
    tile_combos = _gen_tile_combos(m_hint, n_hint, k_hint, max_block_dim)

    for block_m, block_n, block_k in tile_combos:
        # EVEN_K: keep using the *original* (possibly symbolic) k.
        # For dynamic k, (k % block_k == 0) evaluates to False via sympy
        # structural equality, which correctly selects the masked K-loop
        # path — safe for any runtime K value.
        even_k = (k % block_k == 0)
        # GROUP_M: largest factor of num_blocks_m ≤ 8 (guarantees
        # num_blocks_m % GROUP_M == 0, safe for NPU super-grouping).
        num_blocks_m = (m_hint + block_m - 1) // block_m
        group_m = _choose_group_m(num_blocks_m)
        # num_stages based on K-loop iterations (deeper pipeline for
        # many K iters, per optimization_summary.md).
        k_iters = (k_hint + block_k - 1) // block_k
        stages_list = _select_num_stages(k_iters, block_k)
        for num_stages in stages_list:
            configs.append({
                "BLOCK_M": block_m,
                "BLOCK_N": block_n,
                "BLOCK_K": block_k,
                "GROUP_M": group_m,
                "num_stages": num_stages,
                "num_warps": 4,
                "ALLOW_TF32": "False",
                "ACC_TYPE": "tl.float32",
                "EVEN_K": even_k,
            })

    return configs


def add_npu_triton_mm_choices(
    choices: List[ir.ChoiceCaller],
    layout: "ir.Layout",
    mat1: "ir.IRNode",
    mat2: "ir.IRNode",
    m: int,
    n: int,
    k: int,
) -> None:
    """Add NPU Triton matmul template choices to the choices list.

    Generates multiple TritonTemplateCaller choices from the NPU triton mm
    template with different tiling configs, enabling the autotune mechanism
    to select the best config.
    """
    input_nodes = [mat1, mat2]
    configs = _get_npu_mm_configs(m, n, k)

    for cfg in configs:
        # Extract kernel launch params (not passed as constexpr defines)
        num_stages = cfg.pop("num_stages")
        num_warps = cfg.pop("num_warps")

        try:
            choice = npu_triton_mm_template.generate(
                input_nodes=input_nodes,
                layout=layout,
                num_stages=num_stages,
                num_warps=num_warps,
                **cfg,
            )
            if choice is not None:
                choices.append(choice)
        except Exception as e:
            log.debug(
                "Failed to generate NPU triton mm choice with config %s: %s",
                cfg,
                e,
            )


def _choose_group_m(num_blocks_m: int) -> int:
    """Choose GROUP_M as the largest factor of num_blocks_m not exceeding 8.

    This guarantees num_blocks_m % GROUP_M == 0, so the super-grouping
    tile assignment never needs runtime % runtime (which hangs the NPU
    Triton backend).  Falls back to 1 if no larger factor exists.
    """
    for g in [8, 4, 2, 1]:
        if num_blocks_m % g == 0:
            return g
    return 1


def _get_npu_persistent_mm_configs(
    m: int,
    n: int,
    k: int,
) -> List[Dict[str, Any]]:
    """Generate tiling configs for the NPU persistent triton matmul template.

    Each config includes NUM_BLOCKS_M, NUM_BLOCKS_N, NUM_BLOCKS, GROUP_M,
    WIDTH, NUM_SMS and NUM_TILES_PER_PROGRAM which are required by the
    persistent + super-grouping kernel strategy.

    Key invariants:
      * GROUP_M is always a factor of NUM_BLOCKS_M, so all modulo /
        integer-division operations in the template are
        (runtime value) % (compile-time constant) — safe for the NPU backend.
      * NUM_SMS and NUM_TILES_PER_PROGRAM are compile-time constants
        (required for the outer loop bound).

    .. note::
        The persistent kernel bakes ``NUM_BLOCKS``, ``NUM_TILES_PER_PROGRAM``,
        ``WIDTH``, ``NUM_BLOCKS_M`` and ``NUM_BLOCKS_N`` into the kernel as
        ``tl.constexpr``.  These **must** match the actual runtime shape:

        * ``NUM_BLOCKS`` too small → output tiles missed → **wrong results**
        * ``NUM_TILES_PER_PROGRAM`` too small → tiles not covered →
          **wrong results**
        * ``WIDTH`` / ``GROUP_M`` derived from wrong ``NUM_BLOCKS_N`` →
          tiles mapped to wrong ``(pid_m, pid_n)`` → **wrong results**

        For dynamic (symbolic) shapes we cannot guarantee these compile-time
        constants match the runtime shape, so the persistent template is
        **skipped** and the non-persistent template (which computes the grid
        at runtime) is used instead.
    """
    # --- Dynamic-shape guard ---
    # If any of M, N, K is symbolic, we cannot safely determine the
    # compile-time tile constants.  Return an empty config list so that
    # no persistent-mm choices are added; the non-persistent template
    # (npu_triton_mm_template) will still be available.
    if _is_symbolic_dim(m) or _is_symbolic_dim(n) or _is_symbolic_dim(k):
        log.debug(
            "NPU persistent mm: skipping for dynamic shape "
            "(m=%s, n=%s, k=%s) — compile-time tile constants "
            "cannot be safely determined for symbolic dimensions; "
            "falling back to non-persistent triton mm template.",
            m, n, k,
        )
        return []

    configs: List[Dict[str, Any]] = []

    # Dynamically generate tile combos based on the actual shape
    # (same generator as the non-persistent template, so both templates
    # cover the same padding-eliminating BLOCK_M values).
    tile_combos = _gen_tile_combos(m, n, k, max_block_dim=256)

    for block_m, block_n, block_k in tile_combos:
        num_blocks_m = (m + block_m - 1) // block_m
        num_blocks_n = (n + block_n - 1) // block_n
        num_blocks = num_blocks_m * num_blocks_n

        # Skip if the tile is larger than the matrix (no benefit).
        if num_blocks == 0:
            continue

        # Choose GROUP_M as a factor of num_blocks_m (≤ 8) so that
        # group_size == GROUP_M always holds (no partial last group).
        group_m = _choose_group_m(num_blocks_m)
        width = group_m * num_blocks_n
        even_k = (k % block_k == 0)

        # Choose 2 core counts based on num_blocks (instead of the
        # previous fixed [8, 16, 32, 56]) — this significantly reduces
        # the number of configs while still covering the useful
        # parallelism range.
        if num_blocks >= 56:
            core_options = [56, 32]
        elif num_blocks >= 32:
            core_options = [32, 16]
        elif num_blocks >= 16:
            core_options = [16, 8]
        else:
            core_options = [max(num_blocks, 8)]

        # num_stages based on K-loop iterations.
        k_iters = (k + block_k - 1) // block_k
        stages_list = _select_num_stages(k_iters, block_k)

        for num_cores in core_options:
            # Don't launch more programs than there are blocks
            actual_num_cores = min(num_cores, num_blocks)
            if actual_num_cores == 0:
                continue
            # Compute tiles per program (compile-time constant for loop bound)
            num_tiles_per_program = (num_blocks + actual_num_cores - 1) // actual_num_cores
            for num_stages in stages_list:
                configs.append({
                    "BLOCK_M": block_m,
                    "BLOCK_N": block_n,
                    "BLOCK_K": block_k,
                    "GROUP_M": group_m,
                    "NUM_BLOCKS_M": num_blocks_m,
                    "NUM_BLOCKS_N": num_blocks_n,
                    "NUM_BLOCKS": num_blocks,
                    "WIDTH": width,
                    "NUM_SMS": actual_num_cores,
                    "NUM_TILES_PER_PROGRAM": num_tiles_per_program,
                    "num_stages": num_stages,
                    "num_warps": 4,
                    "ALLOW_TF32": "False",
                    "ACC_TYPE": "tl.float32",
                    "EVEN_K": even_k,
                })

    return configs


def add_npu_persistent_mm_choices(
    choices: List[ir.ChoiceCaller],
    layout: "ir.Layout",
    mat1: "ir.IRNode",
    mat2: "ir.IRNode",
    m: int,
    n: int,
    k: int,
) -> None:
    """Add NPU persistent Triton matmul template choices to the choices list.

    Uses the diagonal core division template (new_triton_mm.py.jinja) which
    supports epilogue fusion via {{store_output}}.
    """
    input_nodes = [mat1, mat2]
    configs = _get_npu_persistent_mm_configs(m, n, k)

    for cfg in configs:
        num_stages = cfg.pop("num_stages")
        num_warps = cfg.pop("num_warps")

        try:
            choice = npu_persistent_mm_template.generate(
                input_nodes=input_nodes,
                layout=layout,
                num_stages=num_stages,
                num_warps=num_warps,
                **cfg,
            )
            if choice is not None:
                choices.append(choice)
        except Exception as e:
            log.debug(
                "Failed to generate NPU persistent mm choice with config %s: %s",
                cfg,
                e,
            )


def add_npu_triton_addmm_choices(
    choices: List[ir.ChoiceCaller],
    layout: "ir.Layout",
    inp: "ir.IRNode",
    mat1: "ir.IRNode",
    mat2: "ir.IRNode",
    m: int,
    n: int,
    k: int,
    alpha: float = 1,
    beta: float = 1,
) -> None:
    """Add NPU Triton addmm template choices to the choices list.

    Reuses the same ``npu_triton_mm_template`` (triton_mm.py.jinja) as plain
    ``mm``.  The bias term is fused into the kernel epilogue via the
    ``prefix_args`` + ``epilogue_fn`` mechanism:

      * ``input_nodes = [inp, mat1, mat2]`` — bias (``inp``) is placed first so
        it becomes a *prefix arg*: it is NOT named in ``{{def_kernel("A", "B")}}``
        but is automatically loaded inside ``{{store_output}}`` and passed to
        ``epilogue_fn``.
      * ``prefix_args=1`` tells the codegen that the first input node is the
        bias/epilogue input (not a matmul operand).
      * ``epilogue_fn=addmm_epilogue(dtype, alpha, beta)`` generates
        ``beta * bias + alpha * acc`` at store time, fusing the addmm bias
        addition into the matmul kernel's epilogue.

    This mirrors how the community ``tuned_addmm`` reuses ``mm_template`` with
    ``prefix_args=1`` and ``addmm_epilogue``.
    """
    # bias first (prefix arg), then the two matmul operands named A, B in jinja
    input_nodes = [inp, mat1, mat2]
    # Use max_block_dim=128 for addmm: the bias epilogue fusion (loading
    # and broadcasting the bias vector) adds register pressure, so 256-dim
    # tiles can cause "cc overflow" on the NPU.
    configs = _get_npu_mm_configs(m, n, k, max_block_dim=128)

    # Build the epilogue function that fuses beta*bias + alpha*acc.
    epilogue_fn = addmm_epilogue(layout.dtype, alpha, beta)

    for cfg in configs:
        # Extract kernel launch params (not passed as constexpr defines)
        num_stages = cfg.pop("num_stages")
        num_warps = cfg.pop("num_warps")

        try:
            choice = npu_triton_mm_template.generate(
                input_nodes=input_nodes,
                layout=layout,
                num_stages=num_stages,
                num_warps=num_warps,
                prefix_args=1,
                epilogue_fn=epilogue_fn,
                **cfg,
            )
            if choice is not None:
                choices.append(choice)
        except Exception as e:
            log.debug(
                "Failed to generate NPU triton addmm choice with config %s: %s",
                cfg,
                e,
            )


def is_contiguous_striding(size, stride) -> bool:
    def is_contiguous_row_major(stride, size) -> bool:
        # to support non-contiguous row-major input
        return V.graph.sizevars.statically_known_equals(stride[1], 1) and \
               V.graph.sizevars.statically_known_equals(stride[0], size[1])

    def is_contiguous_col_major(stride, size) -> bool:
        # to support non-contiguous col-major input
        return V.graph.sizevars.statically_known_equals(stride[0], 1) and \
               V.graph.sizevars.statically_known_equals(stride[1], size[0])

    return (
        is_contiguous_row_major(stride, size)
        or is_contiguous_col_major(stride, size)
    )


def _register_npu_inductor_mm():
    @register_lowering(aten.mm, type_promotion_kind=None)
    def tuned_mm(mat1, mat2, *, layout=None):

        m, n, k, layout, mat1, mat2 = mm_args(mat1, mat2, layout=layout)
        name = "mm"

        aten_layout = layout
        if not inductor_config.max_autotune:
            aten_layout = FlexibleLayout(
                device=layout.device, dtype=layout.dtype, size=layout.size
            )

        # options to tune from
        choices = (
            [aten_mm.bind((mat1, mat2), aten_layout)] if use_aten_gemm_kernels() else []
        )
        _, is_nonzero = _is_static_problem(layout)

        is_contiguous_input = (
            is_contiguous_striding(mat1.get_size(), mat1.get_stride())
            and is_contiguous_striding(mat2.get_size(), mat2.get_stride())
        )
        if (
            is_contiguous_input
            and is_nonzero
            and use_catlass_template("mm", layout, m, n, k)
        ):
            CATLASS1xGemmTemplate.add_catlass_gemm_choices(
                choices, layout, [mat1, mat2]
            )
            # debug log
            log.info(f"Choices number after catlass template: {len(choices)}")

        if is_nonzero and use_ck_gemm_template(layout, m, n, k):
            CKGemmTemplate.add_ck_gemm_choices(choices, layout, [mat1, mat2])

        if use_cpp_gemm_template(layout, mat1, mat2):
            CppGemmTemplate.add_choices(
                choices,
                layout,
                [mat1, mat2],
            )

        # Add NPU Triton matmul template choices for CV (Compute/Vector) fusion.
        # The triton template supports epilogue fusion: when the matmul output
        # is consumed by pointwise ops (e.g. add, relu), the scheduler fuses
        # them into the kernel's epilogue via {{store_output}}.
        if is_nonzero and use_triton_template(layout):
            try:
                add_npu_triton_mm_choices(
                    choices, layout, mat1, mat2, m, n, k
                )
                log.debug(
                    "NPU Triton CV fusion: added triton mm template choices "
                    "for mm(%d, %d, %d), total choices now %d",
                    m,
                    n,
                    k,
                    len(choices),
                )
            except Exception as e:
                log.warning("Failed to add NPU triton mm template choices: %s", e)

        # Add NPU persistent Triton matmul template choices.
        # Uses new_triton_mm.py.jinja with a persistent kernel strategy:
        # each program serially processes multiple output tiles, improving
        # L2 cache reuse via super-grouping and reducing launch overhead.
        # Best for large matrices where num_tiles >> num_cores.
        # Also supports epilogue fusion via {{store_output}}.
        if is_nonzero and use_triton_template(layout):
            try:
                add_npu_persistent_mm_choices(
                    choices, layout, mat1, mat2, m, n, k
                )
                log.debug(
                    "NPU persistent mm: added persistent mm template choices "
                    "for mm(%d, %d, %d), total choices now %d",
                    m,
                    n,
                    k,
                    len(choices),
                )
            except Exception as e:
                log.warning("Failed to add NPU persistent mm template choices: %s", e)

        input_nodes = [mat1, mat2]

        if (
            len(choices) == 0
            and not use_aten_gemm_kernels()
            and inductor_config.autotune_fallback_to_aten
        ):
            log.warning("No choices for GEMM, using ATen backend as fallback")
            return aten_mm.bind((mat1, mat2), aten_layout).output_node()

        for k in inductor_config.external_matmul:
            choices.append(lazy_register_extern_choice(k).bind((mat1, mat2), layout))

        try:
            return autotune_select_algorithm(name, choices, [mat1, mat2], layout)
        except NoValidChoicesError:
            if not inductor_config.autotune_fallback_to_aten:
                raise
            log.warning(
                "All choices for GEMM were invalid, using ATen backend as fallback"
            )
            return aten_mm.bind((mat1, mat2), aten_layout).output_node()


def _register_npu_inductor_addmm():
    @register_lowering(aten.addmm, type_promotion_kind=None)
    def tuned_addmm(inp, mat1, mat2, *, alpha=1, beta=1, layout=None):

        # Fallback addmm using fallback handler before mm_args(), if there is no valid catlass template.
        # In case, aten_addmm.bind would decompose addmm to broadcast + mm + add.
        shape1 = mat1.shape
        shape2 = mat2.shape
        bias_shape = inp.shape
        m0 = shape1[0]
        k0 = shape1[1]
        n0 = shape2[1]

        if layout is None:
            from torch._inductor.ir import FixedLayout

            layout_tmp = FixedLayout(
                mat1.get_device(),
                mat1.get_dtype(),
                [m0, n0],
            )

        static_shape_tmp, is_nonzero_tmp = _is_static_problem(layout_tmp if layout is None else layout)

        if not (static_shape_tmp and is_nonzero_tmp):
            return fallback_handler(aten.addmm.default)(inp, mat1, mat2, alpha=alpha, beta=beta)

        try:
            is_contiguous_input_tmp = (
                is_contiguous_striding(mat1.get_size(), mat1.get_stride())
                and is_contiguous_striding(mat2.get_size(), mat2.get_stride())
            )
        except NotImplementedError:
            is_contiguous_input_tmp = False

        # Determine whether the catlass template is available for this problem.
        # We no longer fall back immediately when catlass is unavailable: the
        # NPU Triton addmm template (reusing npu_triton_mm_template with
        # prefix_args=1 + addmm_epilogue) can still be tried below.
        catlass_available = (
            is_contiguous_input_tmp
            and use_catlass_template("addmm", layout_tmp if layout is None else layout, m0, n0, k0)
        )
        # Determine whether the NPU Triton template is available.
        triton_available = is_contiguous_input_tmp and use_triton_template(
            layout_tmp if layout is None else layout
        )

        # If neither catlass nor triton templates are available, fall back.
        if not (catlass_available or triton_available):
            return fallback_handler(aten.addmm.default)(inp, mat1, mat2, alpha=alpha, beta=beta)

        ordered_kwargs_for_cpp_kernel = ("beta", "alpha")
        m, n, k, layout, mat1, mat2, inp_expanded = mm_args(
            mat1, mat2, inp, layout=layout
        )
        static_shape, is_nonzero = _is_static_problem(layout)
        if (not is_nonzero) or (not inductor_config.max_autotune):
            if isinstance(layout, FixedLayout):
                layout = FlexibleLayout(
                    device=layout.device, dtype=layout.dtype, size=layout.size
                )
            choices = (
                [
                    aten_addmm.bind(
                        (inp, mat1, mat2),
                        layout,
                        alpha=alpha,
                        beta=beta,
                    )
                ]
                if use_aten_gemm_kernels()
                else []
            )
            return autotune_select_algorithm(
                "addmm", choices, [inp, mat1, mat2], layout
            )

        choices = (
            [
                aten_addmm.bind(
                    (inp_expanded, mat1, mat2),
                    layout,
                    alpha=alpha,
                    beta=beta,
                )
            ]
            if use_aten_gemm_kernels()
            else []
        )

        is_contiguous_input = (
            is_contiguous_striding(mat1.get_size(), mat1.get_stride())
            and is_contiguous_striding(mat2.get_size(), mat2.get_stride())
        )
        if (
            is_contiguous_input
            and static_shape
            and is_nonzero
            and use_catlass_template("addmm", layout, m, n, k)
        ):
            # Filter out broadcasting on the last dim of the bias term
            # since catlass does not support it yet.
            if (
                PythonWrapperCodegen.statically_known_int_or_none(
                    inp_expanded.layout.stride[-1]
                )
                != 0
            ):
                CATLASS1xGemmTemplate.add_catlass_gemm_choices(
                    choices,
                    layout,
                    [mat1, mat2, inp_expanded],
                    alpha=alpha,
                    beta=beta,
                )

        if is_nonzero and use_ck_gemm_template(layout, m, n, k):
            CKGemmTemplate.add_ck_gemm_choices(
                choices,
                layout,
                [mat1, mat2, inp_expanded],
                alpha=alpha,
                beta=beta,
            )

        if use_cpp_gemm_template(layout, mat1, mat2):
            CppGemmTemplate.add_choices(
                choices,
                layout,
                [inp_expanded, mat1, mat2],
                alpha=alpha,
                beta=beta,
                has_bias=True,
            )

        # Add NPU Triton addmm template choices.
        # Reuses npu_triton_mm_template (triton_mm.py.jinja) with the bias
        # fused into the epilogue via prefix_args=1 + addmm_epilogue.
        # This enables the autotuner to try a Triton kernel for addmm and
        # also supports CV epilogue fusion (e.g. downstream pointwise ops
        # fused into {{store_output}}).
        if is_nonzero and use_triton_template(layout):
            try:
                add_npu_triton_addmm_choices(
                    choices,
                    layout,
                    inp_expanded,
                    mat1,
                    mat2,
                    m,
                    n,
                    k,
                    alpha=alpha,
                    beta=beta,
                )
                log.debug(
                    "NPU Triton CV fusion: added triton addmm template choices "
                    "for addmm(%d, %d, %d), total choices now %d",
                    m,
                    n,
                    k,
                    len(choices),
                )
            except Exception as e:
                log.warning("Failed to add NPU triton addmm template choices: %s", e)

        add_aten_fallback = False
        if len(choices) == 0:
            log.warning("No choices for GEMM, using ATen backend as fallback")
            add_aten_fallback = True

        if add_aten_fallback:
            choices.append(
                aten_addmm.bind(
                    (inp_expanded, mat1, mat2),
                    layout,
                    ordered_kwargs_for_cpp_kernel,
                    alpha=alpha,
                    beta=beta,
                )
            )

        try:
            return autotune_select_algorithm(
                "addmm", choices, [inp_expanded, mat1, mat2], layout
            )
        except NoValidChoicesError:
            if not inductor_config.autotune_fallback_to_aten:
                raise
            log.warning(
                "All choices for GEMM were invalid, using ATen backend as fallback"
            )
            fallback_choice = aten_addmm.bind(
                (inp, mat1, mat2),
                layout,
                ordered_kwargs_for_cpp_kernel,
                alpha=alpha,
                beta=beta,
            )
            return fallback_choice.output_node()
