import functools
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import torch
from torch._inductor.autoheuristic.autoheuristic import AutoHeuristicSelectAlgorithm
from torch._inductor.autoheuristic.autoheuristic_utils import (
    mm_operations,
)
import torch._inductor.codegen
from torch._inductor.codegen.cpp_gemm_template import CppGemmTemplate
import torch._inductor.kernel
from torch._inductor.virtualized import V

from torch._inductor import config as inductor_config, ir
from torch._inductor.codegen.common import BackendFeature
from torch._inductor.codegen.rocm.ck_universal_gemm_template import CKGemmTemplate
from torch._inductor.codegen.wrapper import PythonWrapperCodegen
from torch._inductor.ir import FixedLayout, FlexibleLayout, is_triton
from torch._inductor.lowering import register_lowering, fallback_handler
from torch._inductor.select_algorithm import (
    autotune_select_algorithm,
    ExternKernelChoice,
    NoValidChoicesError,
    TritonTemplate,
)
from torch._inductor.utils import (
    load_template,
    use_aten_gemm_kernels,
    use_ck_gemm_template,
    use_cpp_gemm_template,
    is_pointwise_use,
)
from torch._inductor.kernel.mm_common import (
    _is_static_problem,
    addmm_epilogue,
    mm_args,
    mm_grid,
)

from ..codegen.catlass.gemm_template import CATLASS1xGemmTemplate
from ..select_algorithm import NPUTritonTemplate
from ..utils import use_catlass_template, use_triton_template


log = logging.getLogger("torch._inductor")
aten = torch.ops.aten

lazy_register_extern_choice = torch._inductor.kernel.mm.lazy_register_extern_choice
aten_mm = torch._inductor.kernel.mm.aten_mm
aten_addmm = torch._inductor.kernel.mm.aten_addmm
mm_template = torch._inductor.kernel.mm.mm_template


# ---------------------------------------------------------------------------
# NPU Triton MM Template (for CV / epilogue fusion)
# ---------------------------------------------------------------------------
# Following the community torch design:
#   - The jinja template lives in templates/triton_mm.py.jinja
#   - The NPUTritonTemplate instance is created here, loading that jinja file
#   - Tiling configs are generated by _get_npu_mm_configs() below
#   - Choices are added in tuned_mm() via add_npu_triton_mm_choices()
#
# When the scheduler detects that the matmul output is consumed by pointwise
# ops (add, relu, etc.), it fuses them into the template's {{store_output}}
# epilogue — this is the "CV fusion" mechanism.
# ---------------------------------------------------------------------------

_MM_TEMPLATE = """{{def_kernel("A", "B")}}
    M = {{size("A", 0)}}
    N = {{size("B", 1)}}
    K = {{size("A", 1)}}
    if M * N == 0:
        # early exit due to zero-size input(s)
        return
    stride_am = {{stride("A", 0)}}
    stride_ak = {{stride("A", 1)}}
    stride_bk = {{stride("B", 0)}}
    stride_bn = {{stride("B", 1)}}

    # based on triton.ops.matmul
    pid = tl.program_id(0).to(INDEX_DTYPE)
    grid_m = (M + BLOCK_M - 1) // BLOCK_M
    grid_n = (N + BLOCK_N - 1) // BLOCK_N

    # re-order program ID for better L2 performance
    # Use super-grouping (GROUP_M) for improved L2 cache hit rate
    width = GROUP_M * grid_n
    group_id = pid // width
    group_size = min(grid_m - group_id * GROUP_M, GROUP_M)
    pid_m = group_id * GROUP_M + (pid % group_size)
    pid_n = (pid % width) // group_size

    tl.assume(pid_m >= 0)
    tl.assume(pid_n >= 0)

    rm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    rn = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)

    offs_k = tl.arange(0, BLOCK_K)
    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=ACC_TYPE)

    for k_idx in range(0, tl.cdiv(K, BLOCK_K)):
        offs_a_k = k_idx * BLOCK_K + tl.arange(0, BLOCK_K)
        {% if EVEN_K %}
        a = tl.load(A + (rm[:, None] * stride_am + offs_a_k[None, :] * stride_ak))
        b = tl.load(B + (offs_a_k[:, None] * stride_bk + rn[None, :] * stride_bn))
        {% else %}
        # K is not a multiple of BLOCK_K: mask out-of-bounds elements
        k_mask = offs_a_k < K
        a = tl.load(A + (rm[:, None] * stride_am + offs_a_k[None, :] * stride_ak), mask=k_mask[None, :], other=0.0)
        b = tl.load(B + (offs_a_k[:, None] * stride_bk + rn[None, :] * stride_bn), mask=k_mask[:, None], other=0.0)
        {% endif %}
        acc += tl.dot(a, b, allow_tf32=ALLOW_TF32, out_dtype=ACC_TYPE)

    # rematerialize rm and rn to save registers
    rm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    rn = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    idx_m = rm[:, None]
    idx_n = rn[None, :]
    mask = (idx_m < M) & (idx_n < N)

    # inductor generates a suffix
    {{store_output(("idx_m", "idx_n"), "acc", "mask", val_shape=("BLOCK_M", "BLOCK_N"))}}
"""


npu_triton_mm_template = NPUTritonTemplate(
    name="npu_triton_mm",
    grid=mm_grid,
    source=_MM_TEMPLATE,
    debug=False,
)


def _get_npu_mm_configs(
    m: int,
    n: int,
    k: int,
) -> List[Dict[str, Any]]:
    """Generate tiling configs for NPU triton matmul template.

    Generates a set of (BLOCK_M, BLOCK_N, BLOCK_K, GROUP_M, num_stages,
    num_warps) configurations suitable for NPU hardware.
    """
    configs: List[Dict[str, Any]] = []

    # Core tiling shapes: (BLOCK_M, BLOCK_N, BLOCK_K)
    # Chosen as powers of 2 and multiples of 16 for NPU matrix unit compatibility.
    tile_shapes = [
        (64, 64, 32),
        (64, 128, 32),
        (128, 64, 32),
        (128, 128, 32),
        (64, 64, 64),
        (128, 64, 64),
        (64, 128, 64),
        (32, 64, 32),
        (64, 32, 32),
        (32, 32, 32),
    ]

    for block_m, block_n, block_k in tile_shapes:
        even_k = (k % block_k == 0)
        for group_m in [8]:
            for num_stages in [2, 3]:
                for num_warps in [4, 8]:
                    configs.append({
                        "BLOCK_M": block_m,
                        "BLOCK_N": block_n,
                        "BLOCK_K": block_k,
                        "GROUP_M": group_m,
                        "num_stages": num_stages,
                        "num_warps": num_warps,
                        "ALLOW_TF32": "False",
                        "ACC_TYPE": "tl.float32",
                        "EVEN_K": even_k,
                    })

    return configs


def add_npu_triton_mm_choices(
    choices: List[ir.ChoiceCaller],
    layout: "ir.Layout",
    mat1: "ir.IRNode",
    mat2: "ir.IRNode",
    m: int,
    n: int,
    k: int,
) -> None:
    """Add NPU Triton matmul template choices to the choices list.

    Generates multiple TritonTemplateCaller choices from the NPU triton mm
    template with different tiling configs, enabling the autotune mechanism
    to select the best config.
    """
    input_nodes = [mat1, mat2]
    configs = _get_npu_mm_configs(m, n, k)

    for cfg in configs:
        # Extract kernel launch params (not passed as constexpr defines)
        num_stages = cfg.pop("num_stages")
        num_warps = cfg.pop("num_warps")

        try:
            choice = npu_triton_mm_template.generate(
                input_nodes=input_nodes,
                layout=layout,
                num_stages=num_stages,
                num_warps=num_warps,
                **cfg,
            )
            if choice is not None:
                choices.append(choice)
        except Exception as e:
            log.debug(
                "Failed to generate NPU triton mm choice with config %s: %s",
                cfg,
                e,
            )


def is_contiguous_striding(size, stride) -> bool:
    def is_contiguous_row_major(stride, size) -> bool:
        # to support non-contiguous row-major input
        return V.graph.sizevars.statically_known_equals(stride[1], 1) and \
               V.graph.sizevars.statically_known_equals(stride[0], size[1])

    def is_contiguous_col_major(stride, size) -> bool:
        # to support non-contiguous col-major input
        return V.graph.sizevars.statically_known_equals(stride[0], 1) and \
               V.graph.sizevars.statically_known_equals(stride[1], size[0])

    return (
        is_contiguous_row_major(stride, size)
        or is_contiguous_col_major(stride, size)
    )


def _register_npu_inductor_mm():
    @register_lowering(aten.mm, type_promotion_kind=None)
    def tuned_mm(mat1, mat2, *, layout=None):

        m, n, k, layout, mat1, mat2 = mm_args(mat1, mat2, layout=layout)
        name = "mm"

        aten_layout = layout
        if not inductor_config.max_autotune:
            aten_layout = FlexibleLayout(
                device=layout.device, dtype=layout.dtype, size=layout.size
            )

        # options to tune from
        choices = (
            [aten_mm.bind((mat1, mat2), aten_layout)] if use_aten_gemm_kernels() else []
        )
        _, is_nonzero = _is_static_problem(layout)

        is_contiguous_input = (
            is_contiguous_striding(mat1.get_size(), mat1.get_stride())
            and is_contiguous_striding(mat2.get_size(), mat2.get_stride())
        )
        if (
            is_contiguous_input
            and is_nonzero
            and use_catlass_template("mm", layout, m, n, k)
        ):
            CATLASS1xGemmTemplate.add_catlass_gemm_choices(
                choices, layout, [mat1, mat2]
            )
            # debug log
            log.info(f"Choices number after catlass template: {len(choices)}")

        if is_nonzero and use_ck_gemm_template(layout, m, n, k):
            CKGemmTemplate.add_ck_gemm_choices(choices, layout, [mat1, mat2])

        if use_cpp_gemm_template(layout, mat1, mat2):
            CppGemmTemplate.add_choices(
                choices,
                layout,
                [mat1, mat2],
            )

        # Add NPU Triton matmul template choices for CV (Compute/Vector) fusion.
        # The triton template supports epilogue fusion: when the matmul output
        # is consumed by pointwise ops (e.g. add, relu), the scheduler fuses
        # them into the kernel's epilogue via {{store_output}}.
        if is_nonzero and use_triton_template(layout):
            try:
                add_npu_triton_mm_choices(
                    choices, layout, mat1, mat2, m, n, k
                )
                log.debug(
                    "NPU Triton CV fusion: added triton mm template choices "
                    "for mm(%d, %d, %d), total choices now %d",
                    m,
                    n,
                    k,
                    len(choices),
                )
            except Exception as e:
                log.warning("Failed to add NPU triton mm template choices: %s", e)

        input_nodes = [mat1, mat2]

        if (
            len(choices) == 0
            and not use_aten_gemm_kernels()
            and inductor_config.autotune_fallback_to_aten
        ):
            log.warning("No choices for GEMM, using ATen backend as fallback")
            return aten_mm.bind((mat1, mat2), aten_layout).output_node()

        for k in inductor_config.external_matmul:
            choices.append(lazy_register_extern_choice(k).bind((mat1, mat2), layout))

        try:
            return autotune_select_algorithm(name, choices, [mat1, mat2], layout)
        except NoValidChoicesError:
            if not inductor_config.autotune_fallback_to_aten:
                raise
            log.warning(
                "All choices for GEMM were invalid, using ATen backend as fallback"
            )
            return aten_mm.bind((mat1, mat2), aten_layout).output_node()


def _register_npu_inductor_addmm():
    @register_lowering(aten.addmm, type_promotion_kind=None)
    def tuned_addmm(inp, mat1, mat2, *, alpha=1, beta=1, layout=None):

        # Fallback addmm using fallback handler before mm_args(), if there is no valid catlass template.
        # In case, aten_addmm.bind would decompose addmm to broadcast + mm + add.
        shape1 = mat1.shape
        shape2 = mat2.shape
        bias_shape = inp.shape
        m0 = shape1[0]
        k0 = shape1[1]
        n0 = shape2[1]

        if layout is None:
            from torch._inductor.ir import FixedLayout

            layout_tmp = FixedLayout(
                mat1.get_device(),
                mat1.get_dtype(),
                [m0, n0],
            )

        static_shape_tmp, is_nonzero_tmp = _is_static_problem(layout_tmp if layout is None else layout)

        if not (static_shape_tmp and is_nonzero_tmp):
            return fallback_handler(aten.addmm.default)(inp, mat1, mat2, alpha=alpha, beta=beta)

        try:
            is_contiguous_input_tmp = (
                is_contiguous_striding(mat1.get_size(), mat1.get_stride())
                and is_contiguous_striding(mat2.get_size(), mat2.get_stride())
            )
        except NotImplementedError:
            is_contiguous_input_tmp = False

        if not (
            is_contiguous_input_tmp
            and use_catlass_template("addmm", layout_tmp if layout is None else layout, m0, n0, k0)
        ):
            return fallback_handler(aten.addmm.default)(inp, mat1, mat2, alpha=alpha, beta=beta)

        ordered_kwargs_for_cpp_kernel = ("beta", "alpha")
        m, n, k, layout, mat1, mat2, inp_expanded = mm_args(
            mat1, mat2, inp, layout=layout
        )
        static_shape, is_nonzero = _is_static_problem(layout)
        if (not is_nonzero) or (not inductor_config.max_autotune):
            if isinstance(layout, FixedLayout):
                layout = FlexibleLayout(
                    device=layout.device, dtype=layout.dtype, size=layout.size
                )
            choices = (
                [
                    aten_addmm.bind(
                        (inp, mat1, mat2),
                        layout,
                        alpha=alpha,
                        beta=beta,
                    )
                ]
                if use_aten_gemm_kernels()
                else []
            )
            return autotune_select_algorithm(
                "addmm", choices, [inp, mat1, mat2], layout
            )

        choices = (
            [
                aten_addmm.bind(
                    (inp_expanded, mat1, mat2),
                    layout,
                    alpha=alpha,
                    beta=beta,
                )
            ]
            if use_aten_gemm_kernels()
            else []
        )

        is_contiguous_input = (
            is_contiguous_striding(mat1.get_size(), mat1.get_stride())
            and is_contiguous_striding(mat2.get_size(), mat2.get_stride())
        )
        if (
            is_contiguous_input
            and static_shape
            and is_nonzero
            and use_catlass_template("addmm", layout, m, n, k)
        ):
            # Filter out broadcasting on the last dim of the bias term
            # since catlass does not support it yet.
            if (
                PythonWrapperCodegen.statically_known_int_or_none(
                    inp_expanded.layout.stride[-1]
                )
                != 0
            ):
                CATLASS1xGemmTemplate.add_catlass_gemm_choices(
                    choices,
                    layout,
                    [mat1, mat2, inp_expanded],
                    alpha=alpha,
                    beta=beta,
                )

        if is_nonzero and use_ck_gemm_template(layout, m, n, k):
            CKGemmTemplate.add_ck_gemm_choices(
                choices,
                layout,
                [mat1, mat2, inp_expanded],
                alpha=alpha,
                beta=beta,
            )

        if use_cpp_gemm_template(layout, mat1, mat2):
            CppGemmTemplate.add_choices(
                choices,
                layout,
                [inp_expanded, mat1, mat2],
                alpha=alpha,
                beta=beta,
                has_bias=True,
            )

        add_aten_fallback = False
        if len(choices) == 0:
            log.warning("No choices for GEMM, using ATen backend as fallback")
            add_aten_fallback = True

        if add_aten_fallback:
            choices.append(
                aten_addmm.bind(
                    (inp_expanded, mat1, mat2),
                    layout,
                    ordered_kwargs_for_cpp_kernel,
                    alpha=alpha,
                    beta=beta,
                )
            )

        try:
            return autotune_select_algorithm(
                "addmm", choices, [inp_expanded, mat1, mat2], layout
            )
        except NoValidChoicesError:
            if not inductor_config.autotune_fallback_to_aten:
                raise
            log.warning(
                "All choices for GEMM were invalid, using ATen backend as fallback"
            )
            fallback_choice = aten_addmm.bind(
                (inp, mat1, mat2),
                layout,
                ordered_kwargs_for_cpp_kernel,
                alpha=alpha,
                beta=beta,
            )
            return fallback_choice.output_node()
