whitelist:
  - test/test_as_strided.py
  - test/test_binary_ufuncs.py
  - test/test_ops_unbacked.py
  - test/test_segment_reductions.py
  - test/test_foreach.py
  - test/test_function_schema.py
  - test/test_namedtensor_return_api.py
  - test/test_native_functions.py
  - test/test_type_info.py
  - test/test_type_promotion.py
  - test/torch_np/numpy_tests/core/test_dlpack.py
  - test/torch_np/numpy_tests/core/test_dtype.py
  - test/torch_np/numpy_tests/core/test_einsum.py
  - test/torch_np/numpy_tests/core/test_getlimits.py
  - test/torch_np/numpy_tests/core/test_indexing.py
  - test/torch_np/numpy_tests/core/test_multiarray.py
  - test/torch_np/numpy_tests/core/test_numeric.py
  - test/torch_np/numpy_tests/core/test_numerictypes.py
  - test/torch_np/numpy_tests/core/test_scalar_ctors.py
  - test/torch_np/numpy_tests/core/test_scalar_methods.py
  - test/torch_np/numpy_tests/core/test_scalarinherit.py
  - test/torch_np/numpy_tests/core/test_scalarmath.py
  - test/torch_np/numpy_tests/core/test_shape_base.py
  - test/torch_np/numpy_tests/fft/test_helper.py
  - test/torch_np/numpy_tests/fft/test_pocketfft.py
  - test/torch_np/numpy_tests/lib/test_arraypad.py
  - test/torch_np/numpy_tests/lib/test_arraysetops.py
  - test/torch_np/numpy_tests/lib/test_function_base.py
  - test/torch_np/numpy_tests/lib/test_histograms.py
  - test/torch_np/numpy_tests/lib/test_index_tricks.py
  - test/torch_np/numpy_tests/lib/test_shape_base_.py
  - test/torch_np/numpy_tests/lib/test_twodim_base.py
  - test/torch_np/numpy_tests/lib/test_type_check.py
  - test/torch_np/numpy_tests/linalg/test_linalg.py
  - test/torch_np/test_basic.py
  - test/torch_np/test_binary_ufuncs.py
  - test/torch_np/test_dtype.py
  - test/torch_np/test_function_base.py
  - test/torch_np/test_indexing.py
  - test/torch_np/test_ndarray_methods.py
  - test/torch_np/test_nep50_examples.py
  - test/torch_np/test_random.py
  - test/torch_np/test_reductions.py
  - test/torch_np/test_scalars_0D_arrays.py
  - test/torch_np/test_ufuncs_basic.py
  - test/torch_np/test_unary_ufuncs.py
  - test/test_nestedtensor.py
  - test/test_namedtensor.py
  - test/nn/attention/test_fa3.py
  - test/nn/attention/test_fa4.py
  - test/nn/attention/test_open_registry.py
  - test/nn/test_convolution.py
  - test/nn/test_dropout.py
  - test/nn/test_embedding.py
  - test/nn/test_init.py
  - test/nn/test_lazy_modules.py
  - test/nn/test_load_state_dict.py
  - test/nn/test_module_hooks.py
  - test/nn/test_parametrization.py
  - test/nn/test_pruning.py
  - test/test_modules.py
  - test/test_nnapi.py
  - test/optim/test_lrscheduler.py
  - test/optim/test_optim.py
  - test/optim/test_stateless.py
  - test/optim/test_swa_utils.py
  - test/test_functional_optim.py
  - test/autograd/test_complex.py
  - test/autograd/test_node_lifecycle.py
  - test/test_autograd_fallback.py
  - test/test_functional_autograd_benchmark.py
  - test/test_ops_fwd_gradients.py
  - test/test_ops_gradients.py
  - test/profiler/test_cpp_thread.py
  - test/profiler/test_execution_trace.py
  - test/profiler/test_kineto.py
  - test/profiler/test_memory_profiler.py
  - test/profiler/test_python_tracer.py
  - test/profiler/test_record_function.py
  - test/profiler/test_torch_tidy.py
  - test/profiler/test_trace_validator.py
  - test/profiler/test_xpu_profiler.py
  - test/test_itt.py
  - test/test_throughput_benchmark.py
  - test/distributed/test_c10d_nccl.py
  - test/distributed/test_c10d_ops_nccl.py
  - test/distributed/test_c10d_spawn_nccl.py
  - test/distributed/test_c10d_spawn_ucc.py
  - test/distributed/test_c10d_torchcomms.py
  - test/distributed/test_c10d_ucc.py
  - test/distributed/test_nccl.py
  - test/distributed/test_store.py
  - test/distributed/test_processgroup_jit.py
  - test/distributed/test_multi_threaded_pg.py
  - test/distributed/test_shmem_triton.py
  - test/distributed/test_nvshmem.py
  - test/distributed/test_backends.py
  - test/distributed/bin/test_script.py
  - test/distributed/tensor/test_api.py
  - test/distributed/tensor/test_common_rules.py
  - test/distributed/tensor/test_compile_on_one_rank.py
  - test/distributed/tensor/test_convolution_ops.py
  - test/distributed/tensor/test_decompositions.py
  - test/distributed/tensor/test_dtensor_logging.py
  - test/distributed/tensor/test_dtensor_ops.py
  - test/distributed/tensor/test_dtensor_testbase.py
  - test/distributed/tensor/test_dynamic.py
  - test/distributed/tensor/test_embedding_ops.py
  - test/distributed/tensor/test_experimental_ops.py
  - test/distributed/tensor/test_init.py
  - test/distributed/tensor/test_math_ops.py
  - test/inductor/test_triton_cpu_backend.py
  - test/inductor/test_xpu_basic.py
  - test/distributed/test_inductor_compile_collectives.py
  - test/test_linalg.py
  - test/ao/sparsity/test_structured_sparsifier.py
  - test/test_accelerator.py
  - test/test_matmul_cuda.py
  - test/test_numa_binding.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_misc.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_autocast.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_autograd.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_memory.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_rng.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_storage.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_streams.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_utils.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_profiler.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_ops.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_distributed.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_device.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_testing.py
  - test/cpp_extensions/open_registration_extension/torch_openreg/tests/test_event.py
  - test/test_comparison_utils.py
  - test/test_tensorboard.py

blacklist: []
