v2.4.0


v2.3.1
test_neg_conj_view_logspace_tensor_overload_npu_complex128 (__main__.TestMathBitsPRIVATEUSE1)
test_neg_conj_view_linspace_tensor_overload_npu_complex128 (__main__.TestMathBitsPRIVATEUSE1)
test_neg_conj_view__refs_logspace_tensor_overload_npu_complex128 (__main__.TestMathBitsPRIVATEUSE1)
test_neg_conj_view__refs_linspace_tensor_overload_npu_complex128 (__main__.TestMathBitsPRIVATEUSE1)
test_pointwise_ops_view_as_real_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_pointwise_ops_nn_functional_silu_complex_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_pointwise_ops_imag_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_compare_cpu_view_as_real_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_compare_cpu_complex_npu_float32 (__main__.TestCommonPRIVATEUSE1)

v2.2.0
test_neg_conj_view__refs_logspace_tensor_overload_npu_complex128 (__main__.TestMathBitsPRIVATEUSE1)
test_neg_conj_view__refs_linspace_tensor_overload_npu_complex128 (__main__.TestMathBitsPRIVATEUSE1)
test_pointwise_ops_view_as_real_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_pointwise_ops_nn_functional_silu_complex_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_pointwise_ops_imag_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_out_istft_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_out_imag_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_out__refs_istft_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_out__refs_imag_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_compare_cpu_view_as_real_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_compare_cpu_complex_npu_float32 (__main__.TestCommonPRIVATEUSE1)

v2.1.0
test_pointwise_ops_view_as_real_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_pointwise_ops_nn_functional_silu_complex_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_pointwise_ops_imag_npu_complex64 (__main__.TestFakeTensorPRIVATEUSE1)
test_out_istft_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_out_imag_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_out__refs_istft_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_out__refs_imag_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_compare_cpu_view_as_real_npu_complex64 (__main__.TestCommonPRIVATEUSE1)
test_compare_cpu_complex_npu_float32 (__main__.TestCommonPRIVATEUSE1)
