from .autotune_cache import patch_load_cached_autotuning
from .hints import patch_create_device_properties
from .triton_helpers import *
from .triton_heuristics import patch_triton_heuristics_cached_autotune