name: check_inductor

on:
  workflow_call:
    outputs:
      need_inductor:
        description: "是否需要执行inductor测试用例"
        value: ${{ jobs.inductor.outputs.need_inductor }}

jobs:
  inductor:
    name: inductor
    select: selected_by_default
    runs-on: [ self-hosted, x86, cpu=32 ]
    container:
      image: swr.cn-north-4.myhuaweicloud.com/pytorch_images_x86/pytorchx86:v_03
    outputs:
      need_inductor: ${{ steps.check_inductor.outputs.need_inductor }}
    steps:
      - name: download modify_files.txt
        uses: download-artifact
        with:
          name: modify_files.txt
          path: ./

      - name: run inductor check
        id: check_inductor
        run: |
          ls
          cat modify_files.txt
          need_inductor="no"
          if [ ! -f modify_files.txt ]; then
              echo "check modify file exception!" >&2
          else
              while IFS= read -r modify_file; do
                  if echo "$modify_file" | grep -q -E '_inductor|/interface'; then
                      need_inductor="yes"
                      break
                  fi
              done < modify_files.txt
          fi
          echo "need_inductor=${need_inductor}" >> "$ATOMGIT_OUTPUT"
          echo "need_inductor=${need_inductor}"
