if(ENABLE_D OR ENABLE_ACL)
  file(GLOB _ASCEND_MEM_MANAGER_SRC_LIST RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.cpp")
  set_property(SOURCE ${_ASCEND_MEM_MANAGER_SRC_LIST} PROPERTY COMPILE_DEFINITIONS
    SUBMODULE_ID=fxrt::SubModuleId::SM_DEVICE)
  add_library(_fxrt_ascend_mem_manager_obj OBJECT ${_ASCEND_MEM_MANAGER_SRC_LIST})
endif()