import os
import unittest

os.environ.setdefault("TORCHINDUCTOR_NPU_BACKEND", "triton_experimental")

import torch
from torch._inductor.utils import run_and_get_code
from torch.testing._internal.common_utils import TestCase, run_tests

import torch_npu  # noqa: F401
import torch_npu._inductor  # noqa: F401


EXPERIMENTAL_MARKER = (
    "from torch_npu._inductor.triton_experimental import npu_triton_heuristics"
)


@unittest.skipUnless(torch.npu.is_available(), "requires an NPU")
class TestDynamicShapes(TestCase):
    def setUp(self):
        super().setUp()
        torch._dynamo.reset()

    def tearDown(self):
        torch._dynamo.reset()
        super().tearDown()

    @staticmethod
    def _compile(fn, *args):
        compiled = torch.compile(
            fn,
            dynamic=True,
            options={"npu_backend": "triton_experimental"},
        )
        result, codes = run_and_get_code(compiled, *args)
        if EXPERIMENTAL_MARKER not in "\n".join(codes):
            raise AssertionError("dynamic kernel was not generated by triton_experimental")
        return compiled, result

    def test_dynamic_shape_pointwise_layout(self):
        def fn(x, mask, bias):
            y = torch.where(mask, x + bias, x - bias)
            return y.transpose(0, 1)

        compiled = None
        for rows in (7, 19, 37):
            x = torch.randn(rows, 8, device="npu")
            mask = torch.randint(0, 2, (rows, 1), device="npu", dtype=torch.bool)
            bias = torch.randn(1, 8, device="npu")
            expected = fn(x, mask, bias)
            if compiled is None:
                compiled, actual = self._compile(fn, x, mask, bias)
            else:
                actual = compiled(x, mask, bias)
            torch.testing.assert_close(actual, expected)

    def test_dynamic_shape_reduction(self):
        def fn(x):
            return x.sum(dim=1)

        compiled = None
        for rows in (9, 23, 41):
            x = torch.randn(rows, 16, device="npu")
            expected = fn(x)
            if compiled is None:
                compiled, actual = self._compile(fn, x)
            else:
                actual = compiled(x)
            torch.testing.assert_close(actual, expected, atol=1e-4, rtol=1e-4)

    def test_dynamic_shape_gather_and_scatter(self):
        def fn(x, index, update):
            gathered = torch.gather(x, 1, index)
            return torch.scatter(x, 1, index, update) + gathered

        compiled = None
        for rows in (5, 11, 29):
            x = torch.randn(rows, 8, device="npu")
            index = torch.randint(8, (rows, 8), device="npu", dtype=torch.int64)
            update = torch.randn(rows, 8, device="npu")
            expected = fn(x, index, update)
            if compiled is None:
                compiled, actual = self._compile(fn, x, index, update)
            else:
                actual = compiled(x, index, update)
            torch.testing.assert_close(actual, expected)


if __name__ == "__main__":
    run_tests()
