import os
import unittest

os.environ.setdefault("TORCHINDUCTOR_NPU_BACKEND", "triton_experimental")

import torch
from torch._inductor.utils import run_and_get_code
from torch.testing._internal.common_utils import TestCase, run_tests

import torch_npu  # noqa: F401
import torch_npu._inductor  # noqa: F401


EXPERIMENTAL_MARKER = (
    "from torch_npu._inductor.triton_experimental import npu_triton_heuristics"
)
DEFAULT_MARKER = (
    "import torch_npu._inductor.runtime.triton_heuristics as triton_heuristics"
)


@unittest.skipUnless(torch.npu.is_available(), "requires an NPU")
class TestKernelPatterns(TestCase):
    def setUp(self):
        super().setUp()
        torch._dynamo.reset()

    def tearDown(self):
        torch._dynamo.reset()
        super().tearDown()

    @staticmethod
    def _compile(fn, *args):
        compiled = torch.compile(
            fn,
            options={"npu_backend": "triton_experimental"},
        )
        result, codes = run_and_get_code(compiled, *args)
        full_code = "\n".join(codes)
        if EXPERIMENTAL_MARKER not in full_code:
            raise AssertionError("kernel was not generated by triton_experimental")
        if DEFAULT_MARKER in full_code:
            raise AssertionError("default NPU Triton wrapper was generated")
        return result

    def test_kernel_pointwise_broadcast_view_permute(self):
        def fn(x, mask, bias):
            x = x.view(2, 4, 8)
            y = torch.where(mask, x + bias, x - bias)
            return y.permute(2, 1, 0)

        x = torch.randn(2, 4, 8, device="npu")
        mask = torch.randint(0, 2, (2, 1, 8), device="npu", dtype=torch.bool)
        bias = torch.randn(1, 8, device="npu")
        expected = fn(x, mask, bias)
        actual = self._compile(fn, x, mask, bias)
        torch.testing.assert_close(actual, expected)

    def test_kernel_int64_pointwise(self):
        def fn(x):
            return x * 3 + 7

        x = torch.arange(128, device="npu", dtype=torch.int64)
        expected = fn(x)
        actual = self._compile(fn, x)
        self.assertEqual(actual, expected)

    def test_kernel_expanded_reduction(self):
        def fn(x, y):
            return (x * y).sum((0, 1))

        x = torch.randn(2, 197, 64, device="npu")
        y = torch.randn(2, 1, 64, device="npu")
        expected = fn(x, y)
        actual = self._compile(fn, x, y)
        torch.testing.assert_close(actual, expected, atol=1e-4, rtol=1e-4)

    def test_kernel_gather_and_scatter(self):
        def gather_fn(x, index):
            return torch.gather(x.expand(4, 5, 10, 6), 3, index + 1)

        x = torch.randn(1, 1, 10, 6, device="npu")
        index = torch.randint(5, (4, 5, 10, 1), device="npu", dtype=torch.int64)
        expected = gather_fn(x, index)
        actual = self._compile(gather_fn, x, index)
        torch.testing.assert_close(actual, expected)

        def scatter_fn(x, index, value):
            return torch.scatter(x, 1, index, value).relu()

        target = torch.zeros(2, 3, device="npu")
        scatter_index = torch.tensor([[0], [2]], device="npu", dtype=torch.int64)
        value = torch.ones(2, 3, device="npu")
        expected = scatter_fn(target, scatter_index, value)
        actual = self._compile(scatter_fn, target, scatter_index, value)
        torch.testing.assert_close(actual, expected)

    def test_kernel_tensor_storage_offset(self):
        def fn(x):
            return x[16:32] + 1

        x = torch.randn(1024, device="npu")
        expected = fn(x[128:])
        actual = self._compile(fn, x[128:])
        torch.testing.assert_close(actual, expected)


if __name__ == "__main__":
    run_tests()
