import os
import subprocess
import sys
import tempfile
import textwrap
import unittest


class TestDVMFlexAttention(unittest.TestCase):
    def test_uses_npu_triton_templates(self):
        script = textwrap.dedent(
            r"""
            import math
            import os
            import sys

            import torch
            import torch_npu
            from torch._inductor.utils import run_and_get_code
            from torch.nn.attention.flex_attention import (
                create_block_mask,
                flex_attention,
            )

            try:
                __import__("torch_npu._C.dvm")
            except ImportError as exc:
                print(f"__SKIP__: dvm is not available: {exc}")
                sys.exit(0)


            def causal_mask(_batch, _head, q_idx, kv_idx):
                return q_idx >= kv_idx


            def dense_reference(query, key, value):
                scores = torch.matmul(
                    query.float(), key.float().transpose(-2, -1)
                ) / math.sqrt(query.shape[-1])
                q_idx = torch.arange(
                    query.shape[-2], device=query.device
                )[:, None]
                kv_idx = torch.arange(
                    key.shape[-2], device=query.device
                )[None, :]
                probabilities = torch.softmax(
                    scores.masked_fill(q_idx < kv_idx, float("-inf")), dim=-1
                )
                return torch.matmul(probabilities, value.float()).to(query.dtype)


            torch.npu.set_device(0)
            torch.manual_seed(2026)
            shape = (1, 2, 128, 64)
            inputs = [
                torch.randn(
                    shape,
                    device="npu",
                    dtype=torch.bfloat16,
                    requires_grad=True,
                )
                for _ in range(3)
            ]
            block_mask = create_block_mask(
                causal_mask,
                B=shape[0],
                H=shape[1],
                Q_LEN=shape[2],
                KV_LEN=shape[2],
                device="npu",
            )


            def attention_loss(query, key, value):
                output = flex_attention(
                    query, key, value, block_mask=block_mask
                )
                return output.float().square().mean(), output


            compiled = torch.compile(
                attention_loss,
                backend="inductor",
                fullgraph=True,
                options={"npu_backend": "dvm"},
            )


            def run_compiled(query, key, value):
                loss, output = compiled(query, key, value)
                gradients = torch.autograd.grad(loss, (query, key, value))
                return output, gradients


            (actual, actual_gradients), codes = run_and_get_code(
                run_compiled, *inputs
            )
            reference_inputs = [
                tensor.detach().clone().requires_grad_(True) for tensor in inputs
            ]
            expected = dense_reference(*reference_inputs)
            expected_loss = expected.float().square().mean()
            expected_gradients = torch.autograd.grad(
                expected_loss, reference_inputs
            )

            torch.testing.assert_close(actual, expected, atol=0.03, rtol=0.03)
            for actual_gradient, expected_gradient in zip(
                actual_gradients, expected_gradients
            ):
                torch.testing.assert_close(
                    actual_gradient,
                    expected_gradient,
                    atol=0.08,
                    rtol=0.08,
                )

            code = "\n".join(codes)
            # Kernel names are generated by Inductor and changed between the
            # PyTorch/Triton versions.  Check the generated graph semantics
            # instead of pinning the old template symbol names.
            assert "Original ATen: [flex_attention]" in code, code
            assert "flex_attention_backward" in code, code
            assert "async_compile.triton(" in code, code
            assert "@triton.jit" in code, code
            assert "dvm_fused" in code, code
            assert torch._inductor.config.compile_threads == 1
            print("DVM_TRITON_FLEX_ATTENTION_OK")
            """
        )

        with tempfile.TemporaryDirectory(prefix="dvm_triton_flex_") as tmp_dir:
            env = os.environ.copy()
            env["TORCHINDUCTOR_NPU_BACKEND"] = "dvm"
            env["TORCHINDUCTOR_COMPILE_THREADS"] = "1"
            env["TORCHINDUCTOR_FORCE_DISABLE_CACHES"] = "1"
            env["TORCHINDUCTOR_CACHE_DIR"] = os.path.join(tmp_dir, "cache")
            env["TRITON_CACHE_DIR"] = os.path.join(tmp_dir, "triton")
            proc = subprocess.run(
                [sys.executable, "-c", script],
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )

        if "__SKIP__:" in proc.stdout:
            self.skipTest(proc.stdout.strip())
        self.assertEqual(proc.returncode, 0, proc.stdout)
        self.assertIn("DVM_TRITON_FLEX_ATTENTION_OK", proc.stdout)


if __name__ == "__main__":
    unittest.main()
