import torch
from collections.abc import Callable
from torch._export import aot_compile_warning
import torch.utils._pytree as pytree
from torch.export._tree_utils import reorder_kwargs

def patch_aot_load():
    origin_aot_load = torch._export.aot_load
    def aot_load_npu(so_path: str, device: str) -> Callable:
        """
        Loads a shared library generated by aot_compile and returns a callable

        Args:
            so_path: Path to the shared library

        Returns:
            A callable
        """
        try:
            return origin_aot_load(so_path, device)
        except RuntimeError as e:
            if device == "npu" or device.startswith("npu:"):
                import torch_npu
                runner = torch_npu._C._aoti.AOTIModelContainerRunnerNpu(so_path, 1, device)
            else:
                raise RuntimeError(
                    f"Failed to load model with community logic: {e}"
                ) from e

        def optimized(*args, **kwargs):
            call_spec = runner.get_call_spec()
            in_spec = pytree.treespec_loads(call_spec[0])
            out_spec = pytree.treespec_loads(call_spec[1])
            flat_inputs = pytree.tree_flatten((args, reorder_kwargs(kwargs, in_spec)))[0]
            flat_inputs = [x for x in flat_inputs if isinstance(x, torch.Tensor)]
            flat_outputs = runner.run(flat_inputs)
            return pytree.tree_unflatten(flat_outputs, out_spec)

        return optimized

    torch._export.aot_load = aot_load_npu