name: Nightly Device Full Test (Manual)

on:
  push:
    branches:
      - ci-test
    paths:
      - '.github/workflows/nightly-device-full-test.yml'
  workflow_dispatch:
    inputs:
      device_env:
        description: 'Device environment for test execution (e.g., cpu / privateuse1,cpu)'
        required: false
        default: 'privateuse1'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_nightly_build.yml
    secrets: inherit
    with:
      upstream_repo: pytorch/pytorch
      upstream_ref: main
      torch_npu_repo: Ascend/pytorch
      torch_npu_ref: master
      docker_image: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/pytorch:torch-npu-test-aarch64-cann-a3-py3.10-torch-master-202608290444-503883d4
      report_to_upstream: false
      runner_label: 'linux-aarch64-cpu-24'
      max_jobs: '23'

  test:
    needs: build
    uses: ./.github/workflows/_nightly_test.yml
    secrets: inherit
    with:
      resolved_short: ${{ needs.build.outputs.resolved_short }}
      resolved_sha: ${{ needs.build.outputs.resolved_sha }}
      upstream_repo: pytorch/pytorch
      torch_npu_short: ${{ needs.build.outputs.torch_npu_short }}
      case_paths_config: .github/config/nightly_test_categories.yml
      docker_image: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/pytorch:torch-npu-test-aarch64-cann-a3-py3.10-torch-master-202608290444-503883d4
      report_to_upstream: false
      hw_classification: ''
      full_scan: true
      device_env: ${{ github.event.inputs.device_env || 'privateuse1' }}
      runner_label: 'linux-aarch64-a3-800i-2-cn12-001'
      skip_list: |-
        .github/config/disabled_testcases.json
        .github/config/running_skiped_testcases.json
