name: Nightly Build and Test A5 (All)

on:
  push:
    branches:
      - ci-test
    paths:
      - '.github/workflows/nightly-a5.yml'
      - '.github/config/nightly_test_categories_a5.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_nightly_build.yml
    secrets: inherit
    with:
      upstream_repo: pytorch/pytorch
      upstream_ref: main
      torch_npu_repo: Ascend/pytorch
      torch_npu_ref: master
      docker_image: swr.cn-north-4.myhuaweicloud.com/frameworkptadapter/pytorch:torch-npu-test-x86_64-cann-a5-py3.10-torch-master-cann9.2.0-20260910200430-202609230925-00b993fc
      report_to_upstream: false
      runner_label: 'linux-amd64-a5-2'
      max_jobs: '23'

  test:
    needs: build
    uses: ./.github/workflows/_nightly_test.yml
    secrets: inherit
    with:
      resolved_short: ${{ needs.build.outputs.resolved_short }}
      resolved_sha: ${{ needs.build.outputs.resolved_sha }}
      wheels_tarball: ${{ needs.build.outputs.wheels_tarball }}
      upstream_repo: pytorch/pytorch
      torch_npu_short: ${{ needs.build.outputs.torch_npu_short }}
      case_paths_config: .github/config/nightly_test_categories.yml
      docker_image: swr.cn-north-4.myhuaweicloud.com/frameworkptadapter/pytorch:torch-npu-test-x86_64-cann-a5-py3.10-torch-master-cann9.2.0-20260910200430-202609230925-00b993fc
      report_to_upstream: false
      hw_classification: ''
      full_scan: true
      device_env: 'privateuse1,cpu'
      runner_label: 'linux-amd64-a5-2'

