# Note:
# Same runner only needs one job named like .*fetch-and-rebase

name: Ascend NPU

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  linux-py3_8-fetch-and-rebase:
    name: linux-py3_8-7.0.RC1.alpha005
    uses: ./.github/workflows/_fetch_and_rebase.yml
    with:
      runner: self-hosted
      loop: 10

  linux-py3_8-build-and-test:
    name: linux-py3_8-7.0.RC1.alpha005
    uses: ./.github/workflows/_build-and-test.yml
    needs: linux-py3_8-fetch-and-rebase
    with:
      runner: self-hosted
      devices: --device /dev/davinci6
      image: ascendai/cann:7.1-openeuler2203sp2
