name: Test Build Trigger

on:
  push:
    branches:
      - ci-test

concurrency:
  group: test-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      upstream_repo: pytorch/pytorch
      upstream_sha: 32d3da3df9f98fcc75739253142d85a6dfb6180b
      torch_npu_repo: ${{ github.repository }}
      torch_npu_ref: ci-test
