name: Test Build Trigger

on:
  push:
    branches:
      - ci-test
  workflow_dispatch:

concurrency:
  group: test-build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      upstream_repo: pytorch/pytorch
      upstream_ref: main
      torch_npu_repo: Ascend/pytorch
      torch_npu_ref: ci-test
