name: Test Build Trigger

on:
  push:
    branches:
      - ci-test

concurrency:
  group: test-build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      upstream_repo: pytorch/pytorch
      upstream_sha: 65082aaa4571aae5cc2cfa2b62fa5db650abbe8c
      torch_npu_repo: ${{ github.repository }}
      torch_npu_ref: ci-test
