name: Decoupled Test Pipeline

on:
  pull_request:
    paths:
      - '.github/**'
      - 'test_upstream/**'
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      pytorch_commit:
        description: 'PyTorch commit to checkout for test source'
        required: false
        type: string
        default: 'fad74248e78716152917a729adb2b44ba2bab16e'

jobs:
  trigger_test:
    uses: ./.github/workflows/_torch-npu-upstream-test.yml
    with:
      distributed_shards: '5'
      regular_shards: '5'
      test_files: ''
      pytorch_commit: ${{ inputs.pytorch_commit || 'fad74248e78716152917a729adb2b44ba2bab16e' }}
